version: "3.9"

services:
  php:
    build:
      context: .
      target: development
    volumes:
    - ./:/app

  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - 80:80
    volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./:/app

  mysql:
    image: mysql:8.2.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
